// src/lib/scenarios/index.ts
// Conversation scenarios for each level

import type { Scenario } from '@/types';

export const SCENARIOS: Scenario[] = [
  // ─── BEGINNER ─────────────────────────────────────────────────────────────
  {
    id: 'beg-01',
    level: 'beginner',
    title: 'Ordering Food at a Restaurant',
    description: 'Practice ordering your favorite meal at a casual restaurant.',
    context: 'You are at a local restaurant. The waiter will take your order.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hello! Welcome to Sunrise Café. My name is Alex, and I'll be your server today. Are you ready to order?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "Yes, I am ready!" or "Can I see the menu, please?"',
        expectedKeywords: ['ready', 'menu', 'order', 'yes'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Great! We have a wonderful special today — grilled chicken with rice and vegetables. We also have pasta, sandwiches, and our famous burgers. What would you like?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say what you want to eat. Example: "I would like the grilled chicken, please."',
        expectedKeywords: ['like', 'want', 'order', 'please', 'chicken', 'pasta', 'burger'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Excellent choice! Would you like something to drink? We have water, juice, coffee, and soda.",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Ask for a drink. Example: "I will have an orange juice, please."',
        expectedKeywords: ['water', 'juice', 'coffee', 'soda', 'drink', 'have'],
      },
      {
        id: 't7',
        speaker: 'ai',
        text: "Perfect! So that's one grilled chicken and a drink. Is there anything else I can get for you?",
      },
      {
        id: 't8',
        speaker: 'user',
        text: '',
        hint: 'Say "No, that\'s all, thank you!" or ask for something extra.',
        expectedKeywords: ['no', 'all', 'thank', 'that', 'fine', 'nothing'],
      },
      {
        id: 't9',
        speaker: 'ai',
        text: "Wonderful! Your order will be ready in about 15 minutes. Enjoy your meal!",
      },
    ],
  },
  {
    id: 'beg-02',
    level: 'beginner',
    title: 'Introducing Yourself',
    description: 'Make a great first impression by introducing yourself clearly.',
    context: 'You are at a new school/workplace and meeting someone for the first time.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hi there! I don't think we've met before. I'm Sarah. Nice to meet you!",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Introduce yourself: "Hi Sarah! I\'m [your name]. Nice to meet you too!"',
        expectedKeywords: ['hi', 'hello', 'name', 'nice', 'meet', 'i\'m'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Great to meet you! So, where are you from originally?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say where you are from. Example: "I\'m from Jakarta, Indonesia."',
        expectedKeywords: ['from', 'live', 'city', 'country', 'born', 'jakarta', 'indonesia'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Oh wow, that's amazing! What do you do for work or study?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Talk about your job or studies. Example: "I\'m a student" or "I work as a teacher."',
        expectedKeywords: ['student', 'work', 'study', 'job', 'teacher', 'engineer', 'manager'],
      },
      {
        id: 't7',
        speaker: 'ai',
        text: "That's really interesting! What do you like to do in your free time?",
      },
      {
        id: 't8',
        speaker: 'user',
        text: '',
        hint: 'Share a hobby. Example: "I enjoy reading books and watching movies."',
        expectedKeywords: ['like', 'enjoy', 'love', 'hobby', 'music', 'sports', 'reading', 'watching'],
      },
      {
        id: 't9',
        speaker: 'ai',
        text: "That sounds so fun! I hope we can chat more. It was really lovely meeting you!",
      },
    ],
  },

  // ─── INTERMEDIATE ──────────────────────────────────────────────────────────
  {
    id: 'int-01',
    level: 'intermediate',
    title: 'Job Interview Preparation',
    description: 'Practice answering common interview questions with confidence.',
    context: 'You are being interviewed for a mid-level position at a tech company.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Good morning! Please have a seat. I'm the hiring manager, David Chen. Thank you for coming in today. Could you start by telling me a little about yourself and your background?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Give a professional self-introduction covering your experience, skills, and why you\'re here.',
        expectedKeywords: ['experience', 'background', 'skills', 'worked', 'years', 'passionate', 'team'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Impressive! Now, can you tell me about a challenging project you worked on and how you handled it?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Use the STAR method: Situation, Task, Action, Result. Keep it clear and confident.',
        expectedKeywords: ['challenge', 'problem', 'solution', 'team', 'result', 'success', 'learned'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Great example! Where do you see yourself professionally in the next five years?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Talk about your career goals while aligning them with what this company offers.',
        expectedKeywords: ['goal', 'grow', 'lead', 'develop', 'contribute', 'company', 'future', 'years'],
      },
      {
        id: 't7',
        speaker: 'ai',
        text: "That's a well-thought-out answer. Do you have any questions for us?",
      },
      {
        id: 't8',
        speaker: 'user',
        text: '',
        hint: 'Ask a smart question like: "What does success look like for this role in the first 90 days?"',
        expectedKeywords: ['question', 'role', 'team', 'culture', 'success', 'expect', 'opportunity'],
      },
    ],
  },
  {
    id: 'int-02',
    level: 'intermediate',
    title: 'Work Meeting — Project Update',
    description: 'Give a clear status update on your project to your manager.',
    context: 'You are in a weekly team meeting. Your manager asks for a project status update.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Alright team, let's get started. Can you give us a quick update on where the project stands this week?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Start with what has been completed. Example: "We\'ve completed the design phase and started development."',
        expectedKeywords: ['completed', 'finished', 'started', 'progress', 'phase', 'development', 'on track'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Good to hear. Are there any blockers or issues that the team should be aware of?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Mention any risks or challenges honestly. Example: "We\'re facing a delay due to a dependency from the API team."',
        expectedKeywords: ['issue', 'blocker', 'delay', 'challenge', 'risk', 'dependency', 'waiting'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "I see. What's your plan to resolve that?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Propose a concrete action plan. Example: "I\'ll escalate to the API team and set a deadline for their response."',
        expectedKeywords: ['plan', 'resolve', 'escalate', 'contact', 'meeting', 'deadline', 'solution'],
      },
      {
        id: 't7',
        speaker: 'ai',
        text: "Perfect. When do you expect the project to be completed?",
      },
      {
        id: 't8',
        speaker: 'user',
        text: '',
        hint: 'Give a realistic timeline. Example: "We\'re on track to deliver by end of next week, assuming the blocker is resolved."',
        expectedKeywords: ['week', 'deadline', 'deliver', 'estimate', 'track', 'date', 'timeline'],
      },
    ],
  },

  // ─── ADVANCED ──────────────────────────────────────────────────────────────
  {
    id: 'adv-01',
    level: 'advanced',
    title: 'Business Negotiation',
    description: 'Negotiate contract terms with a high-stakes client.',
    context: 'You are a senior account manager negotiating a B2B software contract renewal.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Thank you for meeting with us today. We've reviewed your proposal for contract renewal. While we value the partnership, I have to be honest — the pricing is significantly above what we budgeted for next year. We were hoping for something closer to a 15% reduction.",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Acknowledge their concern, then explain the value you provide before countering. Don\'t concede immediately.',
        expectedKeywords: ['understand', 'value', 'investment', 'ROI', 'results', 'appreciate', 'however', 'consider'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "I appreciate that perspective, but our internal metrics show we could potentially achieve similar results with a lower-cost alternative. Why should we continue with you at this price point?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Differentiate your solution. Mention specific features, support quality, or past results that competitors can\'t match.',
        expectedKeywords: ['differentiate', 'unique', 'support', 'data', 'integration', 'results', 'proven', 'unlike'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Those are fair points. What's the best you can do on pricing while maintaining that level of service?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Offer a structured counter-proposal — perhaps a multi-year deal, volume discount, or bundled services.',
        expectedKeywords: ['offer', 'propose', 'discount', 'multi-year', 'bundle', 'flexible', 'terms', 'structure'],
      },
      {
        id: 't7',
        speaker: 'ai',
        text: "A two-year commitment with a 7% reduction is interesting. Can you also guarantee the same dedicated support team we have now?",
      },
      {
        id: 't8',
        speaker: 'user',
        text: '',
        hint: 'Close the deal confidently. Confirm what you can and can\'t guarantee, then suggest moving forward.',
        expectedKeywords: ['confirm', 'guarantee', 'commit', 'agree', 'document', 'move forward', 'sign', 'proceed'],
      },
    ],
  },
  {
    id: 'adv-02',
    level: 'advanced',
    title: 'Startup Pitch to Investors',
    description: 'Pitch your startup idea to a panel of venture capitalists.',
    context: 'You have 5 minutes to pitch your EdTech startup. An investor asks pointed questions.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "We've read your executive summary. Before we dive in, give me your elevator pitch — 60 seconds, what problem are you solving and why now?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'State the problem clearly, your solution, target market size, and why timing matters. Be concise and compelling.',
        expectedKeywords: ['problem', 'solution', 'market', 'million', 'users', 'growth', 'timing', 'opportunity'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Interesting. The EdTech space is crowded. What's your unfair advantage over established players like Duolingo or Coursera?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Articulate your unique differentiator — technology, distribution, data, or network effects that incumbents can\'t easily replicate.',
        expectedKeywords: ['advantage', 'different', 'proprietary', 'technology', 'AI', 'data', 'niche', 'approach'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Walk me through your unit economics. What's your CAC, LTV, and current monthly burn rate?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Speak confidently about your numbers. If early stage, explain your assumptions and the path to these metrics.',
        expectedKeywords: ['acquisition', 'cost', 'lifetime', 'value', 'burn', 'revenue', 'margin', 'payback'],
      },
      {
        id: 't7',
        speaker: 'ai',
        text: "Let's say we decide to invest. What's your 18-month roadmap and how will you deploy the capital?",
      },
      {
        id: 't8',
        speaker: 'user',
        text: '',
        hint: 'Break down fund allocation clearly: team, product, marketing, operations. Show milestone thinking.',
        expectedKeywords: ['team', 'product', 'marketing', 'hire', 'milestone', 'launch', 'scale', 'allocate'],
      },
    ],
  },
  // ─── NEW BEGINNER SCENARIOS (beg-03 to beg-12) ─────────────────────────────
  {
    id: 'beg-03',
    level: 'beginner',
    title: 'Asking for Directions',
    description: 'Practice asking for directions to the nearest train station.',
    context: 'You are on the street. A local resident is helping you find your way.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Excuse me, you look a bit lost. Do you need some help finding something?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "Yes, please. Where is the train station?"',
        expectedKeywords: ['yes', 'where', 'train', 'station', 'please'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Oh, the train station is quite close. Just walk straight for two blocks, then turn left. It's next to the library. Did you get that?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "Yes, walk straight and turn left. Thank you!"',
        expectedKeywords: ['yes', 'straight', 'left', 'thank', 'library'],
      },
    ],
  },
  {
    id: 'beg-04',
    level: 'beginner',
    title: 'Checking in at a Hotel',
    description: 'Practice checking in at a hotel and asking about breakfast.',
    context: 'You are at the front desk of a hotel. The receptionist is assisting you.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Welcome to the Grand Hotel! How can I help you today?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "Hello, I want to check in. My name is [your name]."',
        expectedKeywords: ['hello', 'check', 'in', 'name', 'have', 'reservation'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Perfect, I found your booking. You have a double room for three nights. Here is your key card. Breakfast is included. Do you have any questions?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Ask: "What time is breakfast?"',
        expectedKeywords: ['what', 'time', 'breakfast', 'when', 'serve'],
      },
    ],
  },
  {
    id: 'beg-05',
    level: 'beginner',
    title: 'Shopping at a Grocery Store',
    description: 'Find and buy fresh ingredients at a local grocery store.',
    context: 'You are shopping for dinner. A store clerk is helping you.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hello! Are you finding everything okay, or can I help you locate some items?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "I am looking for fresh tomatoes and onions."',
        expectedKeywords: ['looking', 'where', 'tomatoes', 'onions', 'find'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Tomatoes are in aisle 2 next to the lettuce, and onions are in the produce section at the back. Will that be all for you?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "Yes, that is all. Thank you for your help!"',
        expectedKeywords: ['yes', 'that', 'all', 'thank', 'help'],
      },
    ],
  },
  {
    id: 'beg-06',
    level: 'beginner',
    title: 'Buying a Train Ticket',
    description: 'Practice buying a train ticket at the station ticket counter.',
    context: 'You are at a train station. The agent is ready to sell you a ticket.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Next in line, please! Where are you traveling today?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "I want a ticket to London, please."',
        expectedKeywords: ['ticket', 'london', 'please', 'go', 'to'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Sure! One-way or round-trip? The next train departs in 20 minutes.",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "One-way ticket, please. How much is it?"',
        expectedKeywords: ['one-way', 'one', 'way', 'how', 'much', 'price', 'cost'],
      },
    ],
  },
  {
    id: 'beg-07',
    level: 'beginner',
    title: 'Describing Your Hobbies',
    description: 'Share what you enjoy doing in your spare time.',
    context: 'You are chatting with a new classmate about weekend plans.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "I really love playing basketball on weekends. How about you? What do you do in your free time?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "I like reading books and watching movies."',
        expectedKeywords: ['like', 'love', 'reading', 'books', 'watching', 'movies', 'play', 'music'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "That sounds very relaxing! Who is your favorite author, or what kind of movies do you enjoy most?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "I like action movies and adventure books."',
        expectedKeywords: ['favorite', 'action', 'adventure', 'movies', 'books', 'enjoy'],
      },
    ],
  },
  {
    id: 'beg-08',
    level: 'beginner',
    title: 'Ordering Coffee at a Café',
    description: 'Order your favorite drink and ask for the Wi-Fi details.',
    context: 'You are at a cozy local coffee shop. The barista is taking your order.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hi! What can I get started for you today?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "Can I have an iced latte, please?"',
        expectedKeywords: ['have', 'iced', 'latte', 'coffee', 'please', 'order'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "You got it! What size would you like? And will that be to go or for here?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "Medium size, to go, please. And what is the Wi-Fi password?"',
        expectedKeywords: ['medium', 'go', 'wi-fi', 'wifi', 'password', 'please'],
      },
    ],
  },
  {
    id: 'beg-09',
    level: 'beginner',
    title: 'Asking for the Time',
    description: 'Ask a stranger for the time and verify bus schedules.',
    context: 'You are waiting at a bus stop and need to check the time.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hello! Nice day to be waiting outside, isn't it?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "Yes, it is. Excuse me, do you have the time?"',
        expectedKeywords: ['yes', 'excuse', 'have', 'time', 'clock', 'what'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Yes, of course! It is exactly a quarter past two. Are you waiting for the number 10 bus?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "Yes, I am. Thank you very much!"',
        expectedKeywords: ['yes', 'thank', 'much', 'bus', 'waiting'],
      },
    ],
  },
  {
    id: 'beg-10',
    level: 'beginner',
    title: 'Making a Doctor Appointment',
    description: 'Schedule a general health checkup with a receptionist.',
    context: 'You are calling a local medical clinic to set up an appointment.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Good morning, Oakridge Medical Center. How can I help you today?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "Hello, I want to make an appointment for a checkup."',
        expectedKeywords: ['hello', 'make', 'appointment', 'checkup', 'see', 'doctor'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Certainly! We have openings this Thursday morning at nine, or Friday afternoon at three. Which day works best for you?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "Thursday morning at nine works for me. Thank you."',
        expectedKeywords: ['thursday', 'morning', 'nine', 'works', 'best', 'appointment'],
      },
    ],
  },
  {
    id: 'beg-11',
    level: 'beginner',
    title: 'Talking About the Weather',
    description: 'Practice casual greeting talk focused on seasonal weather.',
    context: 'You run into your neighbor in the hallway on a rainy morning.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Good morning! Wow, it is really pouring rain out there today, isn't it?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "Good morning! Yes, it is very wet and cold."',
        expectedKeywords: ['good', 'morning', 'yes', 'rain', 'wet', 'cold', 'pouring'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "It sure is. The forecast says it might clear up by this afternoon, though. Let's hope so!",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "I hope so too. Have a nice day!"',
        expectedKeywords: ['hope', 'too', 'have', 'nice', 'day', 'clear'],
      },
    ],
  },
  {
    id: 'beg-12',
    level: 'beginner',
    title: 'Basic Interview Q&A',
    description: 'Respond to standard introducing questions from an interviewer.',
    context: 'You are sitting down for a brief screening chat with a hiring recruiter.',
    xpReward: 50,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hello, thank you for coming in today. Let's start with a simple question: tell me a bit about yourself.",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Say: "My name is [name], and I am a junior developer looking for work."',
        expectedKeywords: ['name', 'am', 'developer', 'hiring', 'looking', 'work', 'background'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Excellent. Why are you interested in joining our company?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say: "I want to learn new skills and contribute to your team."',
        expectedKeywords: ['skills', 'learn', 'team', 'contribute', 'company', 'culture'],
      },
    ],
  },

  // ─── NEW INTERMEDIATE SCENARIOS (int-03 to int-12) ─────────────────────────
  {
    id: 'int-03',
    level: 'intermediate',
    title: 'Rescheduling a Meeting',
    description: 'Request to change the time of a collaborative project sync.',
    context: 'You have a calendar conflict and need to move a meeting with a colleague.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hi, thanks for reaching out. We have our project sync scheduled for tomorrow at 2:00 PM. What seems to be the issue?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Explain that you have an urgent client call and need to reschedule the meeting.',
        expectedKeywords: ['conflict', 'client', 'urgent', 'reschedule', 'move', 'tomorrow'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "I understand. Client calls definitely take priority. I'm fairly flexible tomorrow morning or Thursday afternoon. Do either of those work?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Suggest meeting on Thursday afternoon instead. Ask if 3:00 PM is suitable.',
        expectedKeywords: ['thursday', 'afternoon', 'three', '3', 'work', 'suitable', 'suggest'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Thursday at 3:00 PM works perfectly for me. I'll update the calendar invite right away. Anything else we need to cover before then?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Say: "No, that is all. Thank you for being so understanding."',
        expectedKeywords: ['no', 'all', 'thank', 'calendar', 'understanding', 'appreciate'],
      },
    ],
  },
  {
    id: 'int-04',
    level: 'intermediate',
    title: 'Reporting a Lost Item',
    description: 'File a report for a lost bag at the airport information desk.',
    context: 'You just landed and cannot find your backpack. You are speaking with airport staff.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hello, welcome to Baggage Services. How can I assist you today?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Explain that you cannot find your black backpack from flight QA-402.',
        expectedKeywords: ['lost', 'backpack', 'bag', 'missing', 'flight', 'find', 'cannot'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "I'm sorry to hear that. Can you describe the contents of the backpack and confirm if it has any identifying tags?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Describe the contents (e.g., a laptop, books, clothing) and mention a blue name tag.',
        expectedKeywords: ['laptop', 'clothing', 'books', 'contents', 'blue', 'tag', 'inside'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Got it. We will file a formal report and trace the tag. Could you provide a contact phone number and address where we can deliver it?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Provide a mock phone number and address clearly.',
        expectedKeywords: ['phone', 'address', 'number', 'hotel', 'contact', 'deliver'],
      },
    ],
  },
  {
    id: 'int-05',
    level: 'intermediate',
    title: 'Explaining a Math/Logic Problem',
    description: 'Explain the solution of a simple business calculation to a teammate.',
    context: 'A colleague is confused about how you calculated the project profit margin.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hey, I was reviewing the spreadsheet. How did you get the 25% profit margin for next quarter?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Explain that profit is calculated by subtracting costs from total revenue, then dividing by revenue.',
        expectedKeywords: ['revenue', 'costs', 'subtract', 'divide', 'margin', 'formula'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Ah, okay. So you subtracted the $30,000 cost from the $40,000 revenue. What about the overhead costs?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Explain that overhead costs are already included in the cost breakdown.',
        expectedKeywords: ['overhead', 'included', 'breakdown', 'costs', 'already', 'total'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "That makes sense. Thanks for clarifying! I'll update the slide deck with these details.",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Say: "You are welcome. Let me know if you need anything else."',
        expectedKeywords: ['welcome', 'let', 'know', 'clarify', 'need', 'deck'],
      },
    ],
  },
  {
    id: 'int-06',
    level: 'intermediate',
    title: 'Asking for Project Feedback',
    description: 'Consult your supervisor to get feedback on a draft proposal.',
    context: 'You want to improve a design layout before sending it to a key client.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Thanks for dropping by. I saw the draft design you sent earlier. What specific feedback are you looking for?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Ask if the color palette and font selections look professional enough.',
        expectedKeywords: ['colors', 'fonts', 'professional', 'palette', 'feedback', 'selections'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "The fonts look very clean. However, the colors are a bit bright for a corporate client. Maybe tone down the red accents?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Agree to use a darker blue or gray accent instead to match their brand.',
        expectedKeywords: ['agree', 'blue', 'gray', 'corporate', 'tone down', 'brand'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Yes, navy blue would fit their guidelines much better. Make that change and send me the revised version. Good job!",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Say: "I will make the adjustments and send it to you shortly. Thank you!"',
        expectedKeywords: ['adjustments', 'revised', 'send', 'shortly', 'thank', 'navy'],
      },
    ],
  },
  {
    id: 'int-07',
    level: 'intermediate',
    title: 'Giving Advice to a Friend',
    description: 'Advise a friend who is feeling overwhelmed by their workload.',
    context: 'A coworker/friend shares that they are struggling to meet deadlines.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "I honestly feel like I have too much on my plate. I can't keep up with all these reports and tasks. What should I do?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Suggest making a prioritized list of tasks and talking to their supervisor about deadlines.',
        expectedKeywords: ['prioritize', 'list', 'supervisor', 'manager', 'deadlines', 'talk'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "I'm worried that if I talk to my manager, they might think I'm incompetent. Shouldn't I just work late?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Reassure them that managers prefer honesty to missed deadlines, and working late leads to burnout.',
        expectedKeywords: ['honesty', 'burnout', 'late', 'health', 'deadlines', 'support'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "You make a good point. I'll make a list tonight and set up a chat tomorrow morning. Thanks for listening.",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Say: "Anytime! Let me know if I can help you compile the list."',
        expectedKeywords: ['anytime', 'help', 'list', 'support', 'friend', 'hope'],
      },
    ],
  },
  {
    id: 'int-08',
    level: 'intermediate',
    title: 'Returning a Faulty Product',
    description: 'Request a refund or replacement for a broken home appliance.',
    context: 'You bought a toaster yesterday, but it does not heat up at all.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Welcome to Customer Service. Are you looking to make a return or exchange today?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Explain that the toaster you bought yesterday is faulty and doesn\'t work.',
        expectedKeywords: ['toaster', 'faulty', 'yesterday', 'work', 'broken', 'heat'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "I see. Do you have the original receipt and packaging with you?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Confirm that you have both the receipt and the box with you.',
        expectedKeywords: ['yes', 'have', 'receipt', 'packaging', 'box', 'original'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Perfect. We have the same model in stock for an exchange, or I can issue a full refund back to your card. Which do you prefer?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'State your preference clearly (e.g., refund or exchange).',
        expectedKeywords: ['prefer', 'refund', 'exchange', 'card', 'replacement', 'model'],
      },
    ],
  },
  {
    id: 'int-09',
    level: 'intermediate',
    title: 'Planning a Weekend Trip',
    description: 'Coordinate destination and schedule choices with a travel partner.',
    context: 'You and a friend are planning a small road trip for the upcoming weekend.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Hey! I'm so excited for our trip. Should we drive up to the mountains, or go down to the beach instead?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Express preference for the mountains because the weather is supposed to be cool.',
        expectedKeywords: ['mountains', 'weather', 'cool', 'prefer', 'scenery', 'drive'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Mountains sound great! I'd love to do some hiking. Do you want to leave Friday evening or early Saturday morning?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Suggest Saturday morning to avoid Friday rush hour traffic.',
        expectedKeywords: ['saturday', 'morning', 'traffic', 'rush hour', 'avoid', 'leave'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Good call, traffic on Friday is always a nightmare. I'll prep my car and buy some snacks. Anything else we need to book?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Suggest booking a cabin or hotel tonight.',
        expectedKeywords: ['cabin', 'hotel', 'book', 'tonight', 'reservation', 'stay'],
      },
    ],
  },
  {
    id: 'int-10',
    level: 'intermediate',
    title: 'Expressing Opinions on a Film',
    description: 'Practice discussing character development and plot twists in a movie.',
    context: 'You are chatting with a coworker at lunch about a movie you both watched.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Did you watch the new sci-fi film last night? I thought the special effects were amazing, but the ending was confusing.",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Agree about the effects, and share your view that the ending felt rushed.',
        expectedKeywords: ['effects', 'ending', 'rushed', 'confusing', 'agree', 'plot'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Yes, exactly! They left so many questions unanswered. What did you think about the lead actor's performance?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Say that the lead actor was very convincing and emotional.',
        expectedKeywords: ['actor', 'performance', 'convincing', 'emotional', 'acting', 'role'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Agree, he carried the movie. Would you recommend it to others despite the weak script?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Say: "Yes, but only for the visual effects. It is still worth a watch."',
        expectedKeywords: ['yes', 'recommend', 'visuals', 'watch', 'worth', 'effects'],
      },
    ],
  },
  {
    id: 'int-11',
    level: 'intermediate',
    title: 'Describing a Memorable Holiday',
    description: 'Recount key highlights and cultural experiences from a past vacation.',
    context: 'A friend asks you about the best trip you have ever taken.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "I want to plan a vacation soon. Tell me, what was the most memorable holiday you've ever had?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Mention a trip to Japan, highlighting the delicious food and beautiful temples.',
        expectedKeywords: ['japan', 'trip', 'temples', 'food', 'memorable', 'delicious', 'travel'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Wow, Japan is on my bucket list! Did you find it difficult to navigate the trains or communicate with locals?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Explain that signs were in English and local people were very helpful.',
        expectedKeywords: ['signs', 'english', 'helpful', 'people', 'easy', 'trains', 'locals'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "That is reassuring. I think I'll start looking at flights. What season do you recommend visiting?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Recommend spring for the cherry blossoms or autumn for the colorful leaves.',
        expectedKeywords: ['spring', 'cherry blossoms', 'autumn', 'leaves', 'recommend', 'season'],
      },
    ],
  },
  {
    id: 'int-12',
    level: 'intermediate',
    title: 'Discussing Daily Routines',
    description: 'Share productivity hacks and discuss schedule management.',
    context: 'You are sharing time management tips with a fellow student/colleague.',
    xpReward: 80,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "I've been feeling really unproductive lately. What does your typical daily routine look like?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Explain that you wake up early, block out quiet study hours, and take short breaks.',
        expectedKeywords: ['wake up', 'early', 'study', 'hours', 'breaks', 'routine'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Quiet blocks sound smart. How do you handle distractions, like phone notifications or social media?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Explain that you put your phone on "Do Not Disturb" and use website blockers.',
        expectedKeywords: ['phone', 'disturb', 'notifications', 'blocker', 'distractions', 'focus'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "I need to start doing that. Do you also write down a checklist of tasks every morning?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Say: "Yes, writing a daily checklist helps me stay organized and motivated."',
        expectedKeywords: ['yes', 'checklist', 'tasks', 'organized', 'motivated', 'morning'],
      },
    ],
  },

  // ─── NEW ADVANCED SCENARIOS (adv-03 to adv-12) ─────────────────────────────
  {
    id: 'adv-03',
    level: 'advanced',
    title: 'Handling a Customer Complaint',
    description: 'Resolve an escalation from an upset client regarding a system outage.',
    context: 'You are a team lead. A client is angry because their service went offline.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "This is completely unacceptable! Our online portal was down for four hours this morning. We lost thousands of dollars in potential sales. What is your team doing about this?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Apologize sincerely, explain that the outage was caused by an unexpected database failure, and confirm it is now stable.',
        expectedKeywords: ['apologize', 'sincerely', 'outage', 'database', 'failure', 'stable', 'resolved'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Understanding the cause doesn't recover our lost revenue. We have an SLA that guarantees 99.9% uptime. How do you plan to compensate us for this breach?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Acknowledge the SLA terms and propose issuing a service credit on their next billing cycle as compensation.',
        expectedKeywords: ['sla', 'compensation', 'credit', 'billing', 'billing cycle', 'terms', 'service credit'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "A service credit is the minimum we expect. More importantly, what measures are being put in place to ensure this doesn't happen again next week?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Detail preventative steps: implementing database replication and adding automated failover alerts.',
        expectedKeywords: ['prevent', 'replication', 'failover', 'alerts', 'monitoring', 'redundancy', 'infrastructure'],
      },
    ],
  },
  {
    id: 'adv-04',
    level: 'advanced',
    title: 'Negotiating a Job Offer Salary',
    description: 'Negotiate total compensation, equity, and remote options with HR.',
    context: 'You have been offered a senior position, but the initial salary is below your target.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "We are thrilled to offer you the role. The base salary is $95,000, plus standard benefits. We think this is a highly competitive offer. What are your thoughts?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Express excitement about the role, but mention that based on your experience, you were targeting a base salary of $110,000.',
        expectedKeywords: ['excited', 'experience', 'target', 'base', 'salary', '110,000', 'negotiate'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "I see. Our salary bands for this level are somewhat constrained. The maximum base we could possibly secure approval for is $102,000. Would that be acceptable?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Accept the base if they can supplement it with a signing bonus, equity options, or remote work flexibility.',
        expectedKeywords: ['acceptable', 'signing bonus', 'equity', 'remote', 'flexibility', 'compensation'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "We can certainly look into granting a $5,000 signing bonus and allowing two days of remote work per week. If we put that in writing, are you ready to sign?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Confirm you are ready to accept once the updated written offer is sent. Thank the recruiter.',
        expectedKeywords: ['accept', 'written offer', 'sign', 'thank', 'confirm', 'details'],
      },
    ],
  },
  {
    id: 'adv-05',
    level: 'advanced',
    title: 'Debating Climate Solutions',
    description: 'Engage in a balanced debate on economic growth versus carbon taxation.',
    context: 'You are participating in a panel debate on environmental policy.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Heavy carbon taxes will hurt small businesses and slow down job creation. Shouldn't we rely on green technology innovation driven by free markets instead?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Argue that while market innovation is vital, clear regulations and carbon taxation create the financial incentive to adopt green technology.',
        expectedKeywords: ['regulations', 'carbon tax', 'incentive', 'innovation', 'market', 'adopt'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "But if we impose high taxes, manufacturing companies will simply relocate to countries with looser environmental standards. How do we prevent this carbon leakage?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Suggest implementing carbon border adjustment tariffs on imported goods from countries without carbon pricing.',
        expectedKeywords: ['leakage', 'tariffs', 'imported', 'carbon border', 'pricing', 'border adjustment'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Border tariffs could trigger trade wars and inflate consumer prices. Is it really worth risking economic stability for environmental benchmarks?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Conclude that the long-term economic cost of climate disasters far exceeds short-term transition friction.',
        expectedKeywords: ['climate disaster', 'cost', 'long-term', 'stability', 'transition', 'economic cost'],
      },
    ],
  },
  {
    id: 'adv-06',
    level: 'advanced',
    title: 'Negotiating a Partnership',
    description: 'Establish partnership terms, API access, and mutual revenue shares.',
    context: 'You are negotiating an integration partnership with a software platform.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "We're open to integrating your service into our app directory. However, we expect a 30% revenue share on all customers acquired through this channel. How does that sound?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Propose a tiered revenue share instead, starting at 15% and scaling to 25% as transaction volume increases.',
        expectedKeywords: ['tiered', 'revenue share', '15%', '25%', 'volume', 'transaction', 'scale'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "A tiered structure is feasible, but we will also need dedicated API technical support to ensure the integration remains reliable. Can you guarantee a 24-hour SLA?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Agree to a 24-hour SLA response time for critical integration bugs during weekdays.',
        expectedKeywords: ['sla', 'technical support', 'guarantee', 'weekdays', 'critical', 'bugs'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "That sounds fair. Let's draft a memorandum of understanding (MOU) to outline these revenue terms and support expectations. Who should we contact on your legal team?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Provide mock legal contact details and express enthusiasm for the partnership.',
        expectedKeywords: ['legal', 'contact', 'mou', 'draft', 'partnership', 'enthusiasm', 'collaborate'],
      },
    ],
  },
  {
    id: 'adv-07',
    level: 'advanced',
    title: 'Conducting a Quarterly Review',
    description: 'Discuss KPI targets, financial metrics, and operational goals.',
    context: 'You are presenting Q3 business performance metrics to the company board.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Welcome. Our customer acquisition costs rose by 18% this quarter, while active user growth slowed. How do you explain this variance from our targets?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Explain that the variance is due to seasonal marketing adjustments and increased ad spend competition in key channels.',
        expectedKeywords: ['variance', 'marketing', 'ad spend', 'competition', 'seasonal', 'acquisition cost'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Understood. But if ad costs are rising, our path to profitability will stretch. What strategy are you deploying to improve customer retention?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Detail retention strategies: launching personalized email campaigns and updating the onboarding tutorial.',
        expectedKeywords: ['retention', 'email campaigns', 'onboarding', 'tutorial', 'engagement', 'improve'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Those sound like viable initiatives. What are your projected growth rates for Q4 if these changes are fully implemented?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Project a realistic 10% month-over-month active user growth rate for Q4 based on retention improvements.',
        expectedKeywords: ['projected', 'growth rate', 'q4', 'active users', 'percent', 'retention'],
      },
    ],
  },
  {
    id: 'adv-08',
    level: 'advanced',
    title: 'Resolving Team Conflict',
    description: 'Mediate a resource and timeline dispute between design and development leads.',
    context: 'You are a project manager mediating a deadline dispute between two leads.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "We simply cannot build these complex designs in two weeks! The dev team is already working overtime. Design needs to simplify their layout or we will delay the launch.",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Acknowledge the development workload pressure, and suggest identifying high-priority design elements to build first.',
        expectedKeywords: ['workload', 'pressure', 'priority', 'simplify', 'elements', 'mvp', 'focus'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Simplifying is fine, but we also have to deliver a premium experience. If we cut the animations, the client will be disappointed. Can we push the launch date out by one week?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Explain that the launch date is fixed due to marketing campaigns, so scope reduction is necessary.',
        expectedKeywords: ['launch date', 'fixed', 'marketing', 'scope', 'reduction', 'necessary', 'timeframe'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "If the date is fixed, I guess we'll have to compromise. How about we launch static designs first, and add the animations in the next sprint?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Endorse this compromise, thanking both leads for their flexibility and setting a follow-up alignment sync.',
        expectedKeywords: ['compromise', 'animations', 'sprint', 'thank', 'flexibility', 'sync', 'follow-up'],
      },
    ],
  },
  {
    id: 'adv-09',
    level: 'advanced',
    title: 'Explaining AI Ethics',
    description: 'Discuss data privacy, algorithmic bias, and regulation models.',
    context: 'You are presenting on data privacy rules at an ethics forum.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "AI models trained on public web data often capture societal biases. Shouldn't we halt commercial AI deployment until we have a way to guarantee bias-free outputs?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Argue that halting deployment is impractical; instead, we should focus on building robust audit systems and diverse datasets.',
        expectedKeywords: ['halt', 'audit', 'datasets', 'auditing', 'bias', 'practical', 'diversity'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "Audits are helpful, but who gets to decide what is considered 'biased'? Corporate developers? Or should governments regulate model training directly?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Advocate for a collaborative regulatory body involving researchers, ethicists, and government representatives.',
        expectedKeywords: ['collaborative', 'regulatory', 'body', 'government', 'ethicists', 'researchers', 'standards'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Government regulation often lags behind rapid technological breakthroughs. Won't rigid regulations stifle innovation and put local companies at a disadvantage?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Summarize that thoughtful safety frameworks actually build trust, which is essential for sustainable long-term commercial innovation.',
        expectedKeywords: ['frameworks', 'safety', 'trust', 'innovation', 'sustainable', 'long-term', 'commercial'],
      },
    ],
  },
  {
    id: 'adv-10',
    level: 'advanced',
    title: 'Discussing Economic Inflation',
    description: 'Analyze monetary policies, supply chain shocks, and wage spirals.',
    context: 'You are a financial analyst discussing macroeconomics on a podcast.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Central banks are aggressively raising interest rates to combat inflation, but this risks causing a global recession. Is interest rate hikes really the right tool?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Explain that raising interest rates cools down excessive demand, which is necessary to prevent a runaway wage-price spiral.',
        expectedKeywords: ['interest rates', 'demand', 'inflation', 'wage-price spiral', 'runaway', 'cool down'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "But current inflation was largely triggered by supply chain issues and energy price shocks, not excess demand. Rates can't fix supply chains, can they?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Acknowledge the supply shock origin, but argue that secondary inflation expectations must be anchored using monetary policy.',
        expectedKeywords: ['supply chain', 'shocks', 'monetary', 'monetary policy', 'expectations', 'anchor'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "If expectations anchor, but wages fail to catch up, consumer spending power will shrink. How do we protect low-income families during this transition?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Suggest targeted fiscal support from governments, such as energy subsidies, rather than broad interest rate cuts.',
        expectedKeywords: ['fiscal', 'subsidies', 'support', 'targeted', 'families', 'low-income', 'recession'],
      },
    ],
  },
  {
    id: 'adv-11',
    level: 'advanced',
    title: 'Leading a Product Launch',
    description: 'Lead a brainstorming session on viral loops and marketing channels.',
    context: 'You are a product lead leading a launch brainstorming meeting.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "We're launching the beta version next month. Our budget is tight, so we can't rely on paid ads. How can we build organic viral loops into the product onboarding?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Suggest implementing a referral system that rewards both the referrer and referee with premium storage or bonus features.',
        expectedKeywords: ['referral', 'reward', 'onboarding', 'organic', 'features', 'bonus', 'loops'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "A referral scheme is a classic loop, but it only works if users find immediate value. How do we ensure they reach their 'aha' moment on their first day?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Detail a simplified registration funnel and a guided tutorial showing the primary benefits within 2 minutes.',
        expectedKeywords: ['funnel', 'registration', 'tutorial', 'benefits', 'minutes', 'value', 'simplified'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Reducing friction in onboarding makes sense. Let's design that flow. Should we also launch a waitlist campaign to build early hype?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Approve the waitlist idea, suggesting social media sharing features to boost waiting list queue placement.',
        expectedKeywords: ['waitlist', 'campaign', 'hype', 'sharing', 'queue', 'social media', 'approve'],
      },
    ],
  },
  {
    id: 'adv-12',
    level: 'advanced',
    title: 'Analyzing Marketing Success',
    description: 'Debrief data performance, conversions, and attribution modeling.',
    context: 'You are a growth marketer presenting campaign performance to a brand client.',
    xpReward: 120,
    durationMinutes: 10,
    turns: [
      {
        id: 't1',
        speaker: 'ai',
        text: "Our cost-per-click was low, but the overall landing page conversion rate remained below 1.2%. Where did the funnel fail to convert?",
      },
      {
        id: 't2',
        speaker: 'user',
        text: '',
        hint: 'Analyze that the low conversion indicates a mismatch between the ad messaging and the landing page value proposition.',
        expectedKeywords: ['conversion', 'landing page', 'messaging', 'mismatch', 'proposition', 'value'],
      },
      {
        id: 't3',
        speaker: 'ai',
        text: "That makes sense; the ads promised a free trial, but the landing page asked for a credit card. How should we restructure the layout to lower friction?",
      },
      {
        id: 't4',
        speaker: 'user',
        text: '',
        hint: 'Suggest removing the credit card requirement from the free trial signup and highlighting trust badges.',
        expectedKeywords: ['credit card', 'signup', 'friction', 'trust', 'badges', 'remove', 'highlight'],
      },
      {
        id: 't5',
        speaker: 'ai',
        text: "Excellent. Let's test that change. What attribution model should we use to evaluate our multi-channel ad spend?",
      },
      {
        id: 't6',
        speaker: 'user',
        text: '',
        hint: 'Recommend a linear or position-based attribution model to properly distribute conversion value across all touchpoints.',
        expectedKeywords: ['attribution', 'model', 'linear', 'position-based', 'touchpoints', 'evaluate', 'conversion'],
      },
    ],
  },
];

/** Get scenarios filtered by level */
export function getScenariosByLevel(level: 'beginner' | 'intermediate' | 'advanced'): Scenario[] {
  return SCENARIOS.filter((s) => s.level === level);
}

/** Get a scenario by its ID */
export function getScenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
